// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieReact.Server.Data;

#nullable disable

namespace MovieReact.Server.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieReact.Server.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The sci-fi/horror-thriller takes the phenomenally successful “Alien” franchise back to its roots: While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe. ",
                            Name = "Alien:Romulus",
                            TrailerLink = "https://www.youtube.com/embed/GTNMt84KT0k?si=abeYQEbwF6WbdJSO"
                        },
                        new
                        {
                            Id = 2,
                            Description = "He’s only the stuntman, but he’s stealing the show.",
                            Name = "The Fall Guy",
                            TrailerLink = "https://www.youtube.com/embed/EySdVK0NK1Y?si=xs39l6fz6Q5yeX8S"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Beetlejuice is back!  Oscar-nominated, singular creative visionary Tim Burton and Oscar nominee and star Michael Keaton reunite for Beetlejuice Beetlejuice, the long-awaited sequel to Burton’s award-winning Beetlejuice.",
                            Name = "BEETLEJUICE BEETLEJUICE ",
                            TrailerLink = "https://www.youtube.com/embed/e6yDanmWI1E?si=RHCDG12ejFVXfv3f"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
